### ISSUE TITLE
When configure does not find gmp it produces a non-helpful error messages

### ISSUE THREAD

**Issue by markuspf** [fingolfin/gap#1] opened 2016-10-25 12:42 UTC
```
../../configure: xyes: not found
checking for __gmpz_init in -lgmp... no
configure: error: GNU Multiple Precision Arithmetic Library not found.
    Maybe you want to call configure with the --with-gmp=<path> option?
    This tells configure where to find the GMP library and headers.
    e.g. --with-gmp=/usr/local or --with-gmp=/usr
```

**Comment by fingolfin** [comment] 2016-10-26 21:12
So... what exactly is not helpful about that message? Respectively how could it be more helpful?

(The xyes at the top is caused by something else, by the way, I'll fix that).

**Comment by markuspf** [comment] 2016-10-31 12:36
I was only referring to the "xyes" (which was the thing that I saw). The rest of the message is of course entirely fine.

**Comment by fingolfin** [comment] 2016-11-01 17:13
This should be fixed now, please reopen if it isn't for you.

**Closed as completed by fingolfin** 2016-11-01 17:13 UTC
